// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	DisplayName string `json:"display_name"`
	UserId      string `json:"user_id"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// LogInRequest defines model for LogInRequest.
type LogInRequest struct {
	UserId string `json:"user_id"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	DisplayName string `json:"display_name"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	DisplayName *string    `json:"display_name,omitempty"`
	IsActive    *bool      `json:"is_active,omitempty"`
	UserId      *string    `json:"user_id,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorised defines model for Unauthorised.
type Unauthorised = Error

// CheckIfUserExistsParams defines parameters for CheckIfUserExists.
type CheckIfUserExistsParams struct {
	UserId string `form:"user_id" json:"user_id"`
}

// LogInJSONRequestBody defines body for LogIn for application/json ContentType.
type LogInJSONRequestBody = LogInRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateDisplayNameJSONRequestBody defines body for UpdateDisplayName for application/json ContentType.
type UpdateDisplayNameJSONRequestBody = UpdateUserRequest
