// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, session_token, created_at, expires_at)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, session_token, created_at, expires_at
`

type CreateSessionParams struct {
	UserID       int64
	SessionToken string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

// CreateSession
//
//	INSERT INTO sessions (user_id, session_token, created_at, expires_at)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, user_id, session_token, created_at, expires_at
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.SessionToken,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, display_name, created_at, is_active)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, display_name, created_at, is_active
`

type CreateUserParams struct {
	UserID      string
	DisplayName string
	CreatedAt   time.Time
	IsActive    bool
}

// CreateUser
//
//	INSERT INTO users (user_id, display_name, created_at, is_active)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, user_id, display_name, created_at, is_active
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.DisplayName,
		arg.CreatedAt,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

// DeleteExpiredSessions
//
//	DELETE FROM sessions WHERE expires_at < ?
func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE session_token = ?
`

// DeleteSessionByToken
//
//	DELETE FROM sessions WHERE session_token = ?
func (q *Queries) DeleteSessionByToken(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, sessionToken)
	return err
}

const getActiveUserBySessionToken = `-- name: GetActiveUserBySessionToken :one
SELECT users.id, users.user_id, users.display_name, users.created_at, users.is_active
FROM sessions JOIN users ON sessions.user_id = users.id WHERE session_token = ? AND expires_at > ? AND users.is_active = 1
`

type GetActiveUserBySessionTokenParams struct {
	SessionToken string
	ExpiresAt    time.Time
}

// GetActiveUserBySessionToken
//
//	SELECT users.id, users.user_id, users.display_name, users.created_at, users.is_active
//	FROM sessions JOIN users ON sessions.user_id = users.id WHERE session_token = ? AND expires_at > ? AND users.is_active = 1
func (q *Queries) GetActiveUserBySessionToken(ctx context.Context, arg GetActiveUserBySessionTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserBySessionToken, arg.SessionToken, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getActiveUserByUserID = `-- name: GetActiveUserByUserID :one
SELECT id, user_id, display_name, created_at, is_active FROM users WHERE user_id = ? AND is_active = 1
`

// GetActiveUserByUserID
//
//	SELECT id, user_id, display_name, created_at, is_active FROM users WHERE user_id = ? AND is_active = 1
func (q *Queries) GetActiveUserByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, display_name, created_at, is_active FROM users WHERE user_id = ?
`

// GetUserByUserID
//
//	SELECT id, user_id, display_name, created_at, is_active FROM users WHERE user_id = ?
func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const updateDisplayNameByUserID = `-- name: UpdateDisplayNameByUserID :one
UPDATE users set display_name = ? WHERE user_id = ? AND is_active = 1 RETURNING id, user_id, display_name, created_at, is_active
`

type UpdateDisplayNameByUserIDParams struct {
	DisplayName string
	UserID      string
}

// UpdateDisplayNameByUserID
//
//	UPDATE users set display_name = ? WHERE user_id = ? AND is_active = 1 RETURNING id, user_id, display_name, created_at, is_active
func (q *Queries) UpdateDisplayNameByUserID(ctx context.Context, arg UpdateDisplayNameByUserIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateDisplayNameByUserID, arg.DisplayName, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}
