// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type AiUser struct {
	ID       int64
	GameType string
	AiType   string
	Name     string
}

type Game struct {
	ID           int64
	GameID       string
	GameType     string
	Status       string
	CreatedBy    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	FinishedAt   *time.Time
	StateVersion int64
	State        json.RawMessage
}

type GameEvent struct {
	ID             int64
	GameID         int64
	Position       int64
	SequenceNumber int64
	EventVersion   int64
	EventType      string
	Data           json.RawMessage
	CreatedAt      time.Time
}

type Position struct {
	ID       int64
	GameID   int64
	UserID   *int64
	AiUserID *int64
	Position int64
	JoinedAt time.Time
}

type Session struct {
	ID           int64
	UserID       int64
	SessionToken string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type User struct {
	ID          int64
	UserID      string
	DisplayName string
	CreatedAt   time.Time
	IsActive    bool
}
