// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, display_name, created_at, is_active)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, display_name, created_at, is_active
`

type CreateUserParams struct {
	UserID      string
	DisplayName string
	CreatedAt   time.Time
	IsActive    bool
}

// CreateUser
//
//	INSERT INTO users (user_id, display_name, created_at, is_active)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, user_id, display_name, created_at, is_active
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.DisplayName,
		arg.CreatedAt,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, display_name, created_at, is_active FROM users WHERE user_id = ?
`

// GetUserByUserID
//
//	SELECT id, user_id, display_name, created_at, is_active FROM users WHERE user_id = ?
func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = ? WHERE id = ?
`

type SetUserActiveParams struct {
	IsActive bool
	ID       int64
}

// SetUserActive
//
//	UPDATE users SET is_active = ? WHERE id = ?
func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUserActive, arg.IsActive, arg.ID)
	return err
}
